[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.build]
dependencies = [ "build-clang", "build-gcc" ]

[tasks.build-clang]
dependencies = [ "cmake-clang" ]
command = "cmake"
args = [ "--build", "build" ]

[tasks.build-gcc]
dependencies = [ "cmake-gcc" ]
command = "cmake"
args = [ "--build", "build" ]

[tasks.cmake-clang]
command = "cmake"
args = [
    "-S",
    ".",
    "-B",
    "build",
    "-DCMAKE_CXX_COMPILER=clang++",
]

[tasks.cmake-gcc]
command = "cmake"
args = [
    "-S",
    ".",
    "-B",
    "build",
    "-DCMAKE_CXX_COMPILER=g++",
]

[tasks.lint]
command = "poac"
args = [
    "lint",
    "--exclude", "Catch2",
    "--exclude", "mitama-utest-utilities",
]

[tasks.fmt]
install_crate = "fd-find"
cwd = "./include/"
command = "fd"
args = [
    "-e", "hpp",
    "-e", "cpp",
    "-x", "clang-format", "-i"
]

[tasks.pretty]
dependencies = [
    "fmt",
    "lint",
    "build",
]
