name: Full Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: clang
            cxx: clang++
            ver: 17
          - cc: clang
            cxx: clang++
            ver: 18
          - cc: gcc
            cxx: g++
            ver: 11
          - cc: gcc
            cxx: g++
            ver: 12
          - cc: gcc
            cxx: g++
            ver: 13
    env:
      CC: ${{ matrix.compiler.cc }}-${{ matrix.compiler.ver }}
      CXX: ${{ matrix.compiler.cxx }}-${{ matrix.compiler.ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install CMake
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y -qq pkg-config cmake

      - name: Install Clang
        if: startsWith(matrix.compiler.cxx, 'clang')
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.compiler.ver }}

      - name: Build and test
        run: |
          mkdir build && cd build
          cmake ..
          make
